apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000        # Port inside cluster
      targetPort: 3000 # Port Grafana container is listening on
      nodePort: 32000  # Port to access Grafana from outside
