apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      resources:
        requests:
          memory: "15Mi"   # minimum memory required
          cpu: "100m"      # minimum CPU required
        limits:
          memory: "20Mi"   # max memory allowed
          cpu: "100m"      # max CPU allowed
