apiVersion: v1
kind: Service
metadata:
  name: web-nautilus
spec:
  type: NodePort
  selector:
    # The Pod doesn’t have labels, so we add one in the Pod and match it here
    app: nautilus-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
